# Generated by Django 5.1 on 2024-08-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menoo', '0002_alter_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='logo.avif', upload_to='foods/', verbose_name='Image Food'),
        ),
    ]
