# Generated by Django 5.1 on 2024-08-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menoo', '0003_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Número da mesa'),
        ),
    ]
