# Generated by Django 5.1 on 2024-08-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menoo', '0004_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Description'),
        ),
    ]
