# Generated by Django 5.1 on 2024-09-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menoo', '0007_order_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Aguardando Atendimento', 'Aguardando Atendimento'), ('Visto', 'Visto')], default='Aguardando Atendimento', max_length=22),
        ),
    ]
