# Generated by Django 5.1 on 2024-09-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menoo', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Visto', 'Visto')], default='Aguardando', max_length=22),
        ),
    ]
