# Generated by Django 5.1 on 2024-09-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menoo', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default='Nenhuma observação', verbose_name='Observation'),
        ),
    ]
